name: PR orchestrator

on:
  pull_request:
    branches: [ main ]

concurrency:
  # Only allow one run at a time for any PR
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_normalize_mondo_edit:
    uses: ./.github/workflows/normalize-mondo-edit.yaml
    permissions:
      actions: write
      contents: write
    with:
      pr_branch: ${{ github.event.pull_request.head.ref }}
      same_repo: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}
      pr_number: ${{ github.event.pull_request.number }}
